require_relative 'base/client'
require_relative 'base/response'
require_relative 'base/request_params'
require_relative 'simple_hotel_search/client'
require_relative 'simple_hotel_search/response'
require_relative 'simple_hotel_search/request_params'